#!/usr/bin/env python3
"""
scripts/provision_device.py

Generates a device_config.yaml for a new Raspberry Pi.
Optionally creates a systemd unit file for auto-start at boot.

Usage:
    python scripts/provision_device.py --device-id pi-001 --museum-id demo-library
    python scripts/provision_device.py --device-id pi-001 --broker-host 192.168.1.50 --install-systemd
"""

import argparse
import os
import subprocess
import sys
import uuid
from pathlib import Path

DEVICE_CONFIG_TEMPLATE = """\
# Auto-generated by provision_device.py
device_id: "{device_id}"
museum_id: "{museum_id}"

mqtt:
  broker_host: "{broker_host}"
  broker_port: {broker_port}
  use_tls: false
  tls_ca_cert: ""
  tls_client_cert: ""
  tls_client_key: ""
  keepalive: 60

ble:
  scan_interval_ms: 500
  rssi_threshold: -70
  debounce_seconds: 2.0
  beacon_type: "iBeacon"

audio:
  input_device_index: 0
  sample_rate: 16000
  silence_threshold: 0.01
  silence_duration_ms: 1500
  max_clip_seconds: 10.0

camera:
  resolution: [1280, 720]
  jpeg_quality: 75
  max_payload_kb: 150

tts:
  engine: "pyttsx3"
  rate: 150
  voice_id: null

offline_cache:
  db_path: "/var/museum/cache_{device_id}.db"
  max_exhibits: 50
"""

SYSTEMD_UNIT_TEMPLATE = """\
[Unit]
Description=Museum Tour Agent ({device_id})
After=network-online.target bluetooth.target
Wants=network-online.target bluetooth.target

[Service]
Type=simple
User=pi
WorkingDirectory={install_dir}/device
ExecStart=/usr/bin/python3 {install_dir}/device/agent.py
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
Environment=PYTHONUNBUFFERED=1

[Install]
WantedBy=multi-user.target
"""


def main():
    parser = argparse.ArgumentParser(description="Provision a new museum tour device")
    parser.add_argument("--device-id", required=True, help="Unique device ID (e.g. pi-001)")
    parser.add_argument("--museum-id", default="demo-library", help="Museum ID")
    parser.add_argument("--broker-host", default="localhost", help="MQTT broker hostname or IP")
    parser.add_argument("--broker-port", type=int, default=1883, help="MQTT broker port")
    parser.add_argument("--output-dir", default=".", help="Where to write device_config.yaml")
    parser.add_argument("--install-systemd", action="store_true", help="Install systemd unit (requires sudo)")
    parser.add_argument("--install-dir", default="/opt/museum-tour", help="Installation directory on the Pi")
    args = parser.parse_args()

    # Generate config
    config_content = DEVICE_CONFIG_TEMPLATE.format(
        device_id=args.device_id,
        museum_id=args.museum_id,
        broker_host=args.broker_host,
        broker_port=args.broker_port,
    )

    output_path = Path(args.output_dir) / "device_config.yaml"
    output_path.write_text(config_content)
    print(f"[✓] Written device config: {output_path}")

    # Create offline cache directory
    cache_dir = Path("/var/museum")
    if cache_dir.exists() or os.geteuid() == 0:
        cache_dir.mkdir(parents=True, exist_ok=True)
        print(f"[✓] Cache directory: {cache_dir}")

    # Systemd unit
    if args.install_systemd:
        unit_content = SYSTEMD_UNIT_TEMPLATE.format(
            device_id=args.device_id,
            install_dir=args.install_dir,
        )
        unit_path = f"/etc/systemd/system/museum-agent-{args.device_id}.service"
        try:
            with open(unit_path, "w") as f:
                f.write(unit_content)
            subprocess.run(["systemctl", "daemon-reload"], check=True)
            subprocess.run(["systemctl", "enable", f"museum-agent-{args.device_id}"], check=True)
            print(f"[✓] Systemd unit installed: {unit_path}")
            print(f"    Start with: sudo systemctl start museum-agent-{args.device_id}")
        except PermissionError:
            print("[!] Need sudo to install systemd unit")
            print(f"    Unit content written to: /tmp/museum-agent-{args.device_id}.service")
            with open(f"/tmp/museum-agent-{args.device_id}.service", "w") as f:
                f.write(unit_content)
        except subprocess.CalledProcessError as e:
            print(f"[!] systemctl error: {e}")

    print("\nProvisioning complete.")
    print(f"  Device ID : {args.device_id}")
    print(f"  Museum ID : {args.museum_id}")
    print(f"  Broker    : {args.broker_host}:{args.broker_port}")
    print(f"\nNext steps:")
    print(f"  1. Copy device_config.yaml to the Pi at {args.install_dir}/device/")
    print(f"  2. Install dependencies: pip install -r device/requirements.txt")
    print(f"  3. Run: python device/agent.py")


if __name__ == "__main__":
    main()
